# STEP 3: After creating Lambda manually, uncomment this import block
# import {
#   to = aws_cloudwatch_log_group.lambda
#   id = "/aws/lambda/manually-created-lambda"
# }

# Here we are defining the CloudWatch Log Group associated with the Lambda function. This log group is used to store logs generated by the Lambda function.
resource "aws_cloudwatch_log_group" "lambda" {
  name = "/aws/lambda/manually-created-lambda"
}
